services:
  bot:
    build: .
    container_name: learning-en-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Сохраняем базу данных на хосте
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
